#!/usr/bin/env python3
import sys 
import subprocess
import zlib
import base64
from pathlib import Path

class CmakeProject():
    def __init__(self, nameProject: str, directory: str):
        self.nameProject = nameProject
        self.directory = directory
        
    def __getPath(self) -> Path:
        try:
            if not self.directory:
                raise ValueError("El nombre del directorio es invalido")
        except ValueError as err:
            print(err)    
        
        return Path(self.nameProject).resolve(strict=False)
    

    def createDirectoryStructure(self) -> None:
        baseDir : Path = self.__getPath()
        baseDir.mkdir(exist_ok=True)
        
        for subDir in ["build", "include", "src"]:
            (baseDir / subDir).mkdir(exist_ok=True)
    
    
    def __CompressCodeCmakeList(self) -> str:
        return r"eJxtUU1vwjAMvedXWOqlPQATnHeoQpnQRNnKx3aLssSgbM3HEleCf7/COiGk+WT72c/PdrbHmIx3EPG7MxEtOoKDj8AhkXRaRoLpDFIXgo/ElJVfKKxxxnZWDD0631fNZrmuYTaePhTAQvSfqChfncsQgBeMZbBBunFqIA98OmMJKeer8rkSXGy2ZT0vm3k/r/gXEE31uls21RzW9X1F9b6t6ouCDawXiwKyXUIYJdKPqhdvXCKUGvzhN3d0XZ/1rj1fN33ifMJb6Y4AjEmtBZ5QdSQ/WsxlCAx6S1FNrDRurK5hBqXWYH1EOJgWEyjWL0kyHpGEcartNArdn0aRjwbThQdemuW+3FYw4LcG5W3oWYQP1H/irvg6bfQm23bw8ERRDn5ALR0Z9QfF6ONFxw9QhpMD"

    def __CompressCodeMainC(self) -> str:
        return r"eJxTzsxLzilNSVWwKS5JyczXy7DjUkYWyslMAolxZeaVKOQmZuZplOVnpmgqcFVzKQBBQRFQPE1DySM1Jye/XCE8vygnJSZPSdMaLFuUWlJalKfgGuEZEh8c6uzsGhxszVXLxQUAmeUkBg=="

    def __descompressCode(self, code_compress):
        compress = base64.b64decode(code_compress)
        code = zlib.decompress(compress).decode('utf-8')
        
        return code
    
     
    def createFilesCode(self) -> None:
        pathCmakeLists = self.__getPath() / "CmakeLists.txt"
        pathMainC = self.__getPath() / "src" / "main.c"

        code_CmakeLists = self.__descompressCode(self.__CompressCodeCmakeList())
        code_C = self.__descompressCode(self.__CompressCodeMainC())

        pathAndCode = {
            pathCmakeLists : code_CmakeLists,
            pathMainC      : code_C,
        }

        for path, originalCode in pathAndCode.items():
            with open(path, "+a", encoding='utf-8') as file:
                file.write(originalCode)
            file.close()


    def executeCmake(self) -> None:
        pathProject = self.__getPath()
        
        configCmake = subprocess.run(["cmake", "-B", "build"], cwd=pathProject, capture_output=True, text=True)
        if not configCmake.returncode == 0:
            print(configCmake.stderr)
            return

        print(configCmake.stdout)

        compile_code = subprocess.run(["cmake", "--build", "build"], cwd=pathProject, capture_output=True, text=True)
        if not compile_code.returncode == 0:
            print(configCmake.stderr)
            return
        
        subprocess.run(["./build/app"], cwd=pathProject)

        print(f"COPY AND EXECUTE: cd {pathProject}")
        print("EXCUTE: [cmake --build build] for compile")
        print("Then execute [./build/app] for execute code")
        print("COMPILATION OKK!!")
    

def main() -> None:
    try:
        if not len(sys.argv) == 3:
            raise IndexError
                    
    except IndexError:
        print(f"Usage: [{sys.argv[0]}] [NAME_PROJECT] [DIRECTORY_TO_CREATE]")
        sys.exit(1)
 
    nameProject : str = sys.argv[1]
    dirProject  : str = sys.argv[2]

    createProject = CmakeProject(nameProject, dirProject)
    createProject.createDirectoryStructure()
    createProject.createFilesCode()
    createProject.executeCmake()

if __name__ == '__main__':
    main()
